Vagrant.configure("2") do |config|
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.define "ansible-vm01" do |node|
        node.vm.hostname = "ansible-vm01"
        node.vm.box = "centos/7"
        node.vm.provider "virtualbox" do |provider| 
            provider.memory = "1024"
            provider.cpus = "2"
        end
        node.vm.network "private_network", ip: "192.168.99.100"
        node.vm.provision "ansible" do |ansible|
            ansible.compatibility_mode = "2.0"
            ansible.playbook = "playbook-provision.yml"
        end
    end
    config.vm.define "ansible-vm02" do |node|
        node.vm.hostname = "ansible-vm02"
        node.vm.box = "centos/7"
        node.vm.provider "virtualbox" do |provider| 
            provider.memory = "1024"
            provider.cpus = "2"
        end
        node.vm.network "private_network", ip: "192.168.99.101"
        node.vm.provision "ansible" do |ansible|
            ansible.compatibility_mode = "2.0"
            ansible.playbook = "playbook-provision.yml"
        end
    end
end